[
    {
        "key": "13812.102",
        "timestamp": 1655975437325,
        "data": {
            "dest_ip": "122.114.220.250",
            "dest_port": "443",
            "oper_condition": "",
            "user_id": "",
            "user_name": "",
            "oper_result": "",
            "error_code": "",
            "oper_name": "",
            "terminal_id": "",
            "oper_time": "2022-06-23 17:10:37",
            "oper_type": "",
            "request_headers": "",
            "resource_type": "application/octet-stream",
            "resource_url": "https://www.sass.hk/bootstrap/fonts/glyphicons-halflings-regular.woff2",
            "response_headers": "",
            "response_content": "",
            "sys_id": "www.sass.hk",
            "web_url": "https://www.sass.hk/guide/",
            "oper_method": "GET"
        }
    },
    {
        "key": "15588.28",
        "timestamp": 1655975442815,
        "data": {
            "dest_ip": "202.205.16.145",
            "dest_port": "443",
            "oper_condition": "",
            "user_id": "",
            "user_name": "",
            "oper_result": "",
            "error_code": "",
            "oper_name": "",
            "terminal_id": "",
            "oper_time": "2022-06-23 17:10:42",
            "oper_type": "",
            "request_headers": "",
            "resource_type": "text/css",
            "resource_url": "https://jy.cuc.edu.cn/template/v3/css/edu/font-awesome.min.css",
            "response_headers": "",
            "response_content": "",
            "sys_id": "jy.cuc.edu.cn",
            "web_url": "https://jy.cuc.edu.cn/index.jspa",
            "oper_method": "GET"
        }
    },
    {
        "key": "15588.31",
        "timestamp": 1655975442817,
        "data": {
            "dest_ip": "202.205.16.145",
            "dest_port": "443",
            "oper_condition": "",
            "user_id": "",
            "user_name": "",
            "oper_result": "",
            "error_code": "",
            "oper_name": "",
            "terminal_id": "",
            "oper_time": "2022-06-23 17:10:42",
            "oper_type": "",
            "request_headers": "",
            "resource_type": "text/css",
            "resource_url": "https://jy.cuc.edu.cn/template/v3/css/edu/plugins/chosen.min.css",
            "response_headers": "",
            "response_content": "",
            "sys_id": "jy.cuc.edu.cn",
            "web_url": "https://jy.cuc.edu.cn/index.jspa",
            "oper_method": "GET"
        }
    },
    {
        "key": "15588.32",
        "timestamp": 1655975442819,
        "data": {
            "dest_ip": "202.205.16.145",
            "dest_port": "443",
            "oper_condition": "",
            "user_id": "",
            "user_name": "",
            "oper_result": "",
            "error_code": "",
            "oper_name": "",
            "terminal_id": "",
            "oper_time": "2022-06-23 17:10:42",
            "oper_type": "",
            "request_headers": "",
            "resource_type": "text/css",
            "resource_url": "https://jy.cuc.edu.cn/template/v3/css/edu/plugins/slick.css",
            "response_headers": "",
            "response_content": "",
            "sys_id": "jy.cuc.edu.cn",
            "web_url": "https://jy.cuc.edu.cn/index.jspa",
            "oper_method": "GET"
        }
    },
    {
        "key": "15588.33",
        "timestamp": 1655975442821,
        "data": {
            "dest_ip": "202.205.16.145",
            "dest_port": "443",
            "oper_condition": "",
            "user_id": "",
            "user_name": "",
            "oper_result": "",
            "error_code": "",
            "oper_name": "",
            "terminal_id": "",
            "oper_time": "2022-06-23 17:10:42",
            "oper_type": "",
            "request_headers": "",
            "resource_type": "text/css",
            "resource_url": "https://jy.cuc.edu.cn/template/v3/css/edu/plugins/meanmenu.min.css",
            "response_headers": "",
            "response_content": "",
            "sys_id": "jy.cuc.edu.cn",
            "web_url": "https://jy.cuc.edu.cn/index.jspa",
            "oper_method": "GET"
        }
    },
    {
        "key": "15588.35",
        "timestamp": 1655975442824,
        "data": {
            "dest_ip": "202.205.16.145",
            "dest_port": "443",
            "oper_condition": "",
            "user_id": "",
            "user_name": "",
            "oper_result": "",
            "error_code": "",
            "oper_name": "",
            "terminal_id": "",
            "oper_time": "2022-06-23 17:10:42",
            "oper_type": "",
            "request_headers": "",
            "resource_type": "text/css",
            "resource_url": "https://jy.cuc.edu.cn/template/v3/css/edu/plugins/jquery-ui.min.css",
            "response_headers": "",
            "response_content": "",
            "sys_id": "jy.cuc.edu.cn",
            "web_url": "https://jy.cuc.edu.cn/index.jspa",
            "oper_method": "GET"
        }
    },
    {
        "key": "15588.29",
        "timestamp": 1655975442864,
        "data": {
            "dest_ip": "202.205.16.145",
            "dest_port": "443",
            "oper_condition": "",
            "user_id": "",
            "user_name": "",
            "oper_result": "",
            "error_code": "",
            "oper_name": "",
            "terminal_id": "",
            "oper_time": "2022-06-23 17:10:42",
            "oper_type": "",
            "request_headers": "",
            "resource_type": "text/css",
            "resource_url": "https://jy.cuc.edu.cn/template/v3/css/edu/icofont.css",
            "response_headers": "",
            "response_content": "",
            "sys_id": "jy.cuc.edu.cn",
            "web_url": "https://jy.cuc.edu.cn/index.jspa",
            "oper_method": "GET"
        }
    },
    {
        "key": "15588.30",
        "timestamp": 1655975442869,
        "data": {
            "dest_ip": "202.205.16.145",
            "dest_port": "443",
            "oper_condition": "",
            "user_id": "",
            "user_name": "",
            "oper_result": "",
            "error_code": "",
            "oper_name": "",
            "terminal_id": "",
            "oper_time": "2022-06-23 17:10:42",
            "oper_type": "",
            "request_headers": "",
            "resource_type": "text/css",
            "resource_url": "https://jy.cuc.edu.cn/template/v3/css/edu/plugins/animate.css",
            "response_headers": "",
            "response_content": "",
            "sys_id": "jy.cuc.edu.cn",
            "web_url": "https://jy.cuc.edu.cn/index.jspa",
            "oper_method": "GET"
        }
    },
    {
        "key": "15588.36",
        "timestamp": 1655975442880,
        "data": {
            "dest_ip": "202.205.16.145",
            "dest_port": "443",
            "oper_condition": "v=20210616",
            "user_id": "",
            "user_name": "",
            "oper_result": "",
            "error_code": "",
            "oper_name": "",
            "terminal_id": "",
            "oper_time": "2022-06-23 17:10:42",
            "oper_type": "",
            "request_headers": "",
            "resource_type": "image/png",
            "resource_url": "https://jy.cuc.edu.cn/template/v3/img/tp/logo.png?v=20210616",
            "response_headers": "",
            "response_content": "",
            "sys_id": "jy.cuc.edu.cn",
            "web_url": "https://jy.cuc.edu.cn/index.jspa",
            "oper_method": "GET"
        }
    },
    {
        "key": "15588.132",
        "timestamp": 1655975443530,
        "data": {
            "dest_ip": "",
            "dest_port": "",
            "oper_condition": "",
            "user_id": "",
            "user_name": "",
            "oper_result": "",
            "error_code": "",
            "oper_name": "",
            "terminal_id": "",
            "oper_time": "2022-06-23 17:10:42",
            "oper_type": "",
            "request_headers": "",
            "resource_type": "image/svg+xml",
            "resource_url": "data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%2027%2044'%3E%3Cpath%20d%3D'M0%2C22L22%2C0l2.1%2C2.1L4.2%2C22l19.9%2C19.9L22%2C44L0%2C22L0%2C22L0%2C22z'%20fill%3D'%23ffffff'%2F%3E%3C%2Fsvg%3E",
            "response_headers": "",
            "response_content": "",
            "sys_id": "jy.cuc.edu.cn",
            "web_url": "https://jy.cuc.edu.cn/index.jspa",
            "oper_method": "GET"
        }
    }
]